/**
 * 风格模板库（内嵌数据，自动生成，请勿手改 prompt 文本）。
 *
 * 数据来源：https://github.com/twri/sdxl_prompt_styler （sai.json + twri.json，共 106 条）
 * 许可证：MIT。prompt / negativePrompt 为原文逐字保留，中文名与分类为本项目本地化。
 */

export interface StyleTemplate {
  id: string;              // 原始 name，如 "ads-automotive"
  name: string;            // 简体中文名，2~8 字，准确传神，如 "汽车广告"、"电影感"、"赛博朋克街景"
  category: string;        // 简体中文分类
  prompt: string;          // 原文逐字保留，含 {prompt}
  negativePrompt: string;  // 原文逐字保留
}

export const STYLE_SOURCE_LICENSE = "MIT · twri/sdxl_prompt_styler";

export const STYLE_CATEGORIES: string[] = ["广告","摄影","通用","艺术","未来","游戏","主题","纸艺"];

export const STYLE_LIBRARY: StyleTemplate[] = [
  {
    id: "ads-advertising",
    name: "商业广告",
    category: "广告",
    prompt: "advertising poster style {prompt} . Professional, modern, product-focused, commercial, eye-catching, highly detailed",
    negativePrompt: "noisy, blurry, amateurish, sloppy, unattractive",
  },
  {
    id: "ads-automotive",
    name: "汽车广告",
    category: "广告",
    prompt: "automotive advertisement style {prompt} . sleek, dynamic, professional, commercial, vehicle-focused, high-resolution, highly detailed",
    negativePrompt: "noisy, blurry, unattractive, sloppy, unprofessional",
  },
  {
    id: "ads-corporate",
    name: "企业形象",
    category: "广告",
    prompt: "corporate branding style {prompt} . professional, clean, modern, sleek, minimalist, business-oriented, highly detailed",
    negativePrompt: "noisy, blurry, grungy, sloppy, cluttered, disorganized",
  },
  {
    id: "ads-fashion editorial",
    name: "时尚大片",
    category: "广告",
    prompt: "fashion editorial style {prompt} . high fashion, trendy, stylish, editorial, magazine style, professional, highly detailed",
    negativePrompt: "outdated, blurry, noisy, unattractive, sloppy",
  },
  {
    id: "ads-food photography",
    name: "美食摄影",
    category: "广告",
    prompt: "food photography style {prompt} . appetizing, professional, culinary, high-resolution, commercial, highly detailed",
    negativePrompt: "unappetizing, sloppy, unprofessional, noisy, blurry",
  },
  {
    id: "ads-gourmet food photography",
    name: "精致美食",
    category: "广告",
    prompt: "gourmet food photo of {prompt} . soft natural lighting, macro details, vibrant colors, fresh ingredients, glistening textures, bokeh background, styled plating, wooden tabletop, garnished, tantalizing, editorial quality",
    negativePrompt: "cartoon, anime, sketch, grayscale, dull, overexposed, cluttered, messy plate, deformed",
  },
  {
    id: "ads-luxury",
    name: "奢侈品",
    category: "广告",
    prompt: "luxury product style {prompt} . elegant, sophisticated, high-end, luxurious, professional, highly detailed",
    negativePrompt: "cheap, noisy, blurry, unattractive, amateurish",
  },
  {
    id: "ads-real estate",
    name: "地产广告",
    category: "广告",
    prompt: "real estate photography style {prompt} . professional, inviting, well-lit, high-resolution, property-focused, commercial, highly detailed",
    negativePrompt: "dark, blurry, unappealing, noisy, unprofessional",
  },
  {
    id: "ads-retail",
    name: "商品包装",
    category: "广告",
    prompt: "retail packaging style {prompt} . vibrant, enticing, commercial, product-focused, eye-catching, professional, highly detailed",
    negativePrompt: "noisy, blurry, amateurish, sloppy, unattractive",
  },
  {
    id: "photo-alien",
    name: "异星景观",
    category: "摄影",
    prompt: "alien-themed {prompt} . extraterrestrial, cosmic, otherworldly, mysterious, sci-fi, highly detailed",
    negativePrompt: "earthly, mundane, common, realistic, simple",
  },
  {
    id: "photo-film noir",
    name: "黑色电影",
    category: "摄影",
    prompt: "film noir style {prompt} . monochrome, high contrast, dramatic shadows, 1940s style, mysterious, cinematic",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, vibrant, colorful",
  },
  {
    id: "photo-glamour",
    name: "魅力人像",
    category: "摄影",
    prompt: "glamorous photo {prompt} . high fashion, luxurious, extravagant, stylish, sensual, opulent, elegance, stunning beauty, professional, high contrast, detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, distorted, grainy, sketch, low contrast, dull, plain, modest",
  },
  {
    id: "photo-hdr",
    name: "高动态范围",
    category: "摄影",
    prompt: "HDR photo of {prompt} . High dynamic range, vivid, rich details, clear shadows and highlights, realistic, intense, enhanced contrast, highly detailed",
    negativePrompt: "flat, low contrast, oversaturated, underexposed, overexposed, blurred, noisy",
  },
  {
    id: "photo-iphone photographic",
    name: "手机摄影",
    category: "摄影",
    prompt: "iphone photo {prompt} . large depth of field, deep depth of field, highly detailed",
    negativePrompt: "drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly, shallow depth of field, bokeh",
  },
  {
    id: "photo-long exposure",
    name: "长曝光",
    category: "摄影",
    prompt: "long exposure photo of {prompt} . Blurred motion, streaks of light, surreal, dreamy, ghosting effect, highly detailed",
    negativePrompt: "static, noisy, deformed, shaky, abrupt, flat, low contrast",
  },
  {
    id: "photo-neon noir",
    name: "霓虹夜色",
    category: "摄影",
    prompt: "neon noir {prompt} . cyberpunk, dark, rainy streets, neon signs, high contrast, low light, vibrant, highly detailed",
    negativePrompt: "bright, sunny, daytime, low contrast, black and white, sketch, watercolor",
  },
  {
    id: "photo-silhouette",
    name: "剪影",
    category: "摄影",
    prompt: "silhouette style {prompt} . high contrast, minimalistic, black and white, stark, dramatic",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic",
  },
  {
    id: "photo-tilt-shift",
    name: "移轴微缩",
    category: "摄影",
    prompt: "tilt-shift photo of {prompt} . selective focus, miniature effect, blurred background, highly detailed, vibrant, perspective control",
    negativePrompt: "blurry, noisy, deformed, flat, low contrast, unrealistic, oversaturated, underexposed",
  },
  {
    id: "sai-3d-model",
    name: "三维模型",
    category: "通用",
    prompt: "professional 3d model {prompt} . octane render, highly detailed, volumetric, dramatic lighting",
    negativePrompt: "ugly, deformed, noisy, low poly, blurry, painting",
  },
  {
    id: "sai-analog film",
    name: "胶片质感",
    category: "通用",
    prompt: "analog film photo {prompt} . faded film, desaturated, 35mm photo, grainy, vignette, vintage, Kodachrome, Lomography, stained, highly detailed, found footage",
    negativePrompt: "painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured",
  },
  {
    id: "sai-anime",
    name: "日系动漫",
    category: "通用",
    prompt: "anime artwork {prompt} . anime style, key visual, vibrant, studio anime, highly detailed",
    negativePrompt: "photo, deformed, black and white, realism, disfigured, low contrast",
  },
  {
    id: "sai-cinematic",
    name: "电影感",
    category: "通用",
    prompt: "cinematic film still {prompt} . shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy",
    negativePrompt: "anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured",
  },
  {
    id: "sai-comic book",
    name: "美式漫画",
    category: "通用",
    prompt: "comic {prompt} . graphic illustration, comic art, graphic novel art, vibrant, highly detailed",
    negativePrompt: "photograph, deformed, glitch, noisy, realistic, stock photo",
  },
  {
    id: "sai-craft clay",
    name: "黏土手作",
    category: "通用",
    prompt: "play-doh style {prompt} . sculpture, clay art, centered composition, Claymation",
    negativePrompt: "sloppy, messy, grainy, highly detailed, ultra textured, photo",
  },
  {
    id: "sai-digital art",
    name: "数字绘画",
    category: "通用",
    prompt: "concept art {prompt} . digital artwork, illustrative, painterly, matte painting, highly detailed",
    negativePrompt: "photo, photorealistic, realism, ugly",
  },
  {
    id: "sai-enhance",
    name: "画质增强",
    category: "通用",
    prompt: "breathtaking {prompt} . award-winning, professional, highly detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, distorted, grainy",
  },
  {
    id: "sai-fantasy art",
    name: "奇幻艺术",
    category: "通用",
    prompt: "ethereal fantasy concept art of  {prompt} . magnificent, celestial, ethereal, painterly, epic, majestic, magical, fantasy art, cover art, dreamy",
    negativePrompt: "photographic, realistic, realism, 35mm film, dslr, cropped, frame, text, deformed, glitch, noise, noisy, off-center, deformed, cross-eyed, closed eyes, bad anatomy, ugly, disfigured, sloppy, duplicate, mutated, black and white",
  },
  {
    id: "sai-isometric",
    name: "等距视角",
    category: "通用",
    prompt: "isometric style {prompt} . vibrant, beautiful, crisp, detailed, ultra detailed, intricate",
    negativePrompt: "deformed, mutated, ugly, disfigured, blur, blurry, noise, noisy, realistic, photographic",
  },
  {
    id: "sai-line art",
    name: "线稿",
    category: "通用",
    prompt: "line art drawing {prompt} . professional, sleek, modern, minimalist, graphic, line art, vector graphics",
    negativePrompt: "anime, photorealistic, 35mm film, deformed, glitch, blurry, noisy, off-center, deformed, cross-eyed, closed eyes, bad anatomy, ugly, disfigured, mutated, realism, realistic, impressionism, expressionism, oil, acrylic",
  },
  {
    id: "sai-lowpoly",
    name: "低多边形",
    category: "通用",
    prompt: "low-poly style {prompt} . low-poly game art, polygon mesh, jagged, blocky, wireframe edges, centered composition",
    negativePrompt: "noisy, sloppy, messy, grainy, highly detailed, ultra textured, photo",
  },
  {
    id: "sai-neonpunk",
    name: "霓虹朋克",
    category: "通用",
    prompt: "neonpunk style {prompt} . cyberpunk, vaporwave, neon, vibes, vibrant, stunningly beautiful, crisp, detailed, sleek, ultramodern, magenta highlights, dark purple shadows, high contrast, cinematic, ultra detailed, intricate, professional",
    negativePrompt: "painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured",
  },
  {
    id: "sai-origami",
    name: "折纸艺术",
    category: "通用",
    prompt: "origami style {prompt} . paper art, pleated paper, folded, origami art, pleats, cut and fold, centered composition",
    negativePrompt: "noisy, sloppy, messy, grainy, highly detailed, ultra textured, photo",
  },
  {
    id: "sai-photographic",
    name: "真实摄影",
    category: "通用",
    prompt: "cinematic photo {prompt} . 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    negativePrompt: "drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly",
  },
  {
    id: "sai-pixel art",
    name: "像素风",
    category: "通用",
    prompt: "pixel-art {prompt} . low-res, blocky, pixel art style, 8-bit graphics",
    negativePrompt: "sloppy, messy, blurry, noisy, highly detailed, ultra textured, photo, realistic",
  },
  {
    id: "sai-texture",
    name: "材质贴图",
    category: "通用",
    prompt: "texture {prompt} top down close-up",
    negativePrompt: "ugly, deformed, noisy, blurry",
  },
  {
    id: "artstyle-abstract",
    name: "抽象艺术",
    category: "艺术",
    prompt: "abstract style {prompt} . non-representational, colors and shapes, expression of feelings, imaginative, highly detailed",
    negativePrompt: "realistic, photographic, figurative, concrete",
  },
  {
    id: "artstyle-abstract expressionism",
    name: "抽象表现主义",
    category: "艺术",
    prompt: "abstract expressionist painting {prompt} . energetic brushwork, bold colors, abstract forms, expressive, emotional",
    negativePrompt: "realistic, photorealistic, low contrast, plain, simple, monochrome",
  },
  {
    id: "artstyle-art deco",
    name: "装饰艺术",
    category: "艺术",
    prompt: "art deco style {prompt} . geometric shapes, bold colors, luxurious, elegant, decorative, symmetrical, ornate, detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, modernist, minimalist",
  },
  {
    id: "artstyle-art nouveau",
    name: "新艺术运动",
    category: "艺术",
    prompt: "art nouveau style {prompt} . elegant, decorative, curvilinear forms, nature-inspired, ornate, detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, modernist, minimalist",
  },
  {
    id: "artstyle-constructivist",
    name: "构成主义",
    category: "艺术",
    prompt: "constructivist style {prompt} . geometric shapes, bold colors, dynamic composition, propaganda art style",
    negativePrompt: "realistic, photorealistic, low contrast, plain, simple, abstract expressionism",
  },
  {
    id: "artstyle-cubist",
    name: "立体主义",
    category: "艺术",
    prompt: "cubist artwork {prompt} . geometric shapes, abstract, innovative, revolutionary",
    negativePrompt: "anime, photorealistic, 35mm film, deformed, glitch, low contrast, noisy",
  },
  {
    id: "artstyle-expressionist",
    name: "表现主义",
    category: "艺术",
    prompt: "expressionist {prompt} . raw, emotional, dynamic, distortion for emotional effect, vibrant, use of unusual colors, detailed",
    negativePrompt: "realism, symmetry, quiet, calm, photo",
  },
  {
    id: "artstyle-graffiti",
    name: "街头涂鸦",
    category: "艺术",
    prompt: "graffiti style {prompt} . street art, vibrant, urban, detailed, tag, mural",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic",
  },
  {
    id: "artstyle-hyperrealism",
    name: "超写实",
    category: "艺术",
    prompt: "hyperrealistic art {prompt} . extremely high-resolution details, photographic, realism pushed to extreme, fine texture, incredibly lifelike",
    negativePrompt: "simplified, abstract, unrealistic, impressionistic, low resolution",
  },
  {
    id: "artstyle-impressionist",
    name: "印象派",
    category: "艺术",
    prompt: "impressionist painting {prompt} . loose brushwork, vibrant color, light and shadow play, captures feeling over form",
    negativePrompt: "anime, photorealistic, 35mm film, deformed, glitch, low contrast, noisy",
  },
  {
    id: "artstyle-pointillism",
    name: "点彩派",
    category: "艺术",
    prompt: "pointillism style {prompt} . composed entirely of small, distinct dots of color, vibrant, highly detailed",
    negativePrompt: "line drawing, smooth shading, large color fields, simplistic",
  },
  {
    id: "artstyle-pop art",
    name: "波普艺术",
    category: "艺术",
    prompt: "pop Art style {prompt} . bright colors, bold outlines, popular culture themes, ironic or kitsch",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, minimalist",
  },
  {
    id: "artstyle-psychedelic",
    name: "迷幻艺术",
    category: "艺术",
    prompt: "psychedelic style {prompt} . vibrant colors, swirling patterns, abstract forms, surreal, trippy",
    negativePrompt: "monochrome, black and white, low contrast, realistic, photorealistic, plain, simple",
  },
  {
    id: "artstyle-renaissance",
    name: "文艺复兴",
    category: "艺术",
    prompt: "renaissance style {prompt} . realistic, perspective, light and shadow, religious or mythological themes, highly detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, modernist, minimalist, abstract",
  },
  {
    id: "artstyle-steampunk",
    name: "蒸汽朋克",
    category: "艺术",
    prompt: "steampunk style {prompt} . antique, mechanical, brass and copper tones, gears, intricate, detailed",
    negativePrompt: "deformed, glitch, noisy, low contrast, anime, photorealistic",
  },
  {
    id: "artstyle-surrealist",
    name: "超现实主义",
    category: "艺术",
    prompt: "surrealist art {prompt} . dreamlike, mysterious, provocative, symbolic, intricate, detailed",
    negativePrompt: "anime, photorealistic, realistic, deformed, glitch, noisy, low contrast",
  },
  {
    id: "artstyle-typography",
    name: "字体排印",
    category: "艺术",
    prompt: "typographic art {prompt} . stylized, intricate, detailed, artistic, text-based",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic",
  },
  {
    id: "artstyle-watercolor",
    name: "水彩画",
    category: "艺术",
    prompt: "watercolor painting {prompt} . vibrant, beautiful, painterly, detailed, textural, artistic",
    negativePrompt: "anime, photorealistic, 35mm film, deformed, glitch, low contrast, noisy",
  },
  {
    id: "futuristic-biomechanical",
    name: "生物机械",
    category: "未来",
    prompt: "biomechanical style {prompt} . blend of organic and mechanical elements, futuristic, cybernetic, detailed, intricate",
    negativePrompt: "natural, rustic, primitive, organic, simplistic",
  },
  {
    id: "futuristic-biomechanical cyberpunk",
    name: "生化朋克",
    category: "未来",
    prompt: "biomechanical cyberpunk {prompt} . cybernetics, human-machine fusion, dystopian, organic meets artificial, dark, intricate, highly detailed",
    negativePrompt: "natural, colorful, deformed, sketch, low contrast, watercolor",
  },
  {
    id: "futuristic-cybernetic",
    name: "赛博机械",
    category: "未来",
    prompt: "cybernetic style {prompt} . futuristic, technological, cybernetic enhancements, robotics, artificial intelligence themes",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, historical, medieval",
  },
  {
    id: "futuristic-cybernetic robot",
    name: "赛博机器人",
    category: "未来",
    prompt: "cybernetic robot {prompt} . android, AI, machine, metal, wires, tech, futuristic, highly detailed",
    negativePrompt: "organic, natural, human, sketch, watercolor, low contrast",
  },
  {
    id: "futuristic-cyberpunk cityscape",
    name: "赛博朋克街景",
    category: "未来",
    prompt: "cyberpunk cityscape {prompt} . neon lights, dark alleys, skyscrapers, futuristic, vibrant colors, high contrast, highly detailed",
    negativePrompt: "natural, rural, deformed, low contrast, black and white, sketch, watercolor",
  },
  {
    id: "futuristic-futuristic",
    name: "未来主义",
    category: "未来",
    prompt: "futuristic style {prompt} . sleek, modern, ultramodern, high tech, detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, vintage, antique",
  },
  {
    id: "futuristic-retro cyberpunk",
    name: "复古赛博",
    category: "未来",
    prompt: "retro cyberpunk {prompt} . 80's inspired, synthwave, neon, vibrant, detailed, retro futurism",
    negativePrompt: "modern, desaturated, black and white, realism, low contrast",
  },
  {
    id: "futuristic-retro futurism",
    name: "复古未来",
    category: "未来",
    prompt: "retro-futuristic {prompt} . vintage sci-fi, 50s and 60s style, atomic age, vibrant, highly detailed",
    negativePrompt: "contemporary, realistic, rustic, primitive",
  },
  {
    id: "futuristic-sci-fi",
    name: "科幻场景",
    category: "未来",
    prompt: "sci-fi style {prompt} . futuristic, technological, alien worlds, space themes, advanced civilizations",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, historical, medieval",
  },
  {
    id: "futuristic-vaporwave",
    name: "蒸汽波",
    category: "未来",
    prompt: "vaporwave style {prompt} . retro aesthetic, cyberpunk, vibrant, neon colors, vintage 80s and 90s style, highly detailed",
    negativePrompt: "monochrome, muted colors, realism, rustic, minimalist, dark",
  },
  {
    id: "game-bubble bobble",
    name: "泡泡龙",
    category: "游戏",
    prompt: "Bubble Bobble style {prompt} . 8-bit, cute, pixelated, fantasy, vibrant, reminiscent of Bubble Bobble game",
    negativePrompt: "realistic, modern, photorealistic, violent, horror",
  },
  {
    id: "game-cyberpunk game",
    name: "赛博朋克游戏",
    category: "游戏",
    prompt: "cyberpunk game style {prompt} . neon, dystopian, futuristic, digital, vibrant, detailed, high contrast, reminiscent of cyberpunk genre video games",
    negativePrompt: "historical, natural, rustic, low detailed",
  },
  {
    id: "game-fighting game",
    name: "格斗游戏",
    category: "游戏",
    prompt: "fighting game style {prompt} . dynamic, vibrant, action-packed, detailed character design, reminiscent of fighting video games",
    negativePrompt: "peaceful, calm, minimalist, photorealistic",
  },
  {
    id: "game-gta",
    name: "侠盗猎车",
    category: "游戏",
    prompt: "GTA-style artwork {prompt} . satirical, exaggerated, pop art style, vibrant colors, iconic characters, action-packed",
    negativePrompt: "realistic, black and white, low contrast, impressionist, cubist, noisy, blurry, deformed",
  },
  {
    id: "game-mario",
    name: "马里奥风",
    category: "游戏",
    prompt: "Super Mario style {prompt} . vibrant, cute, cartoony, fantasy, playful, reminiscent of Super Mario series",
    negativePrompt: "realistic, modern, horror, dystopian, violent",
  },
  {
    id: "game-minecraft",
    name: "我的世界",
    category: "游戏",
    prompt: "Minecraft style {prompt} . blocky, pixelated, vibrant colors, recognizable characters and objects, game assets",
    negativePrompt: "smooth, realistic, detailed, photorealistic, noise, blurry, deformed",
  },
  {
    id: "game-pokemon",
    name: "宝可梦",
    category: "游戏",
    prompt: "Pokémon style {prompt} . vibrant, cute, anime, fantasy, reminiscent of Pokémon series",
    negativePrompt: "realistic, modern, horror, dystopian, violent",
  },
  {
    id: "game-retro arcade",
    name: "复古街机",
    category: "游戏",
    prompt: "retro arcade style {prompt} . 8-bit, pixelated, vibrant, classic video game, old school gaming, reminiscent of 80s and 90s arcade games",
    negativePrompt: "modern, ultra-high resolution, photorealistic, 3D",
  },
  {
    id: "game-retro game",
    name: "复古游戏",
    category: "游戏",
    prompt: "retro game art {prompt} . 16-bit, vibrant colors, pixelated, nostalgic, charming, fun",
    negativePrompt: "realistic, photorealistic, 35mm film, deformed, glitch, low contrast, noisy",
  },
  {
    id: "game-rpg fantasy game",
    name: "奇幻角色扮演",
    category: "游戏",
    prompt: "role-playing game (RPG) style fantasy {prompt} . detailed, vibrant, immersive, reminiscent of high fantasy RPG games",
    negativePrompt: "sci-fi, modern, urban, futuristic, low detailed",
  },
  {
    id: "game-strategy game",
    name: "策略游戏",
    category: "游戏",
    prompt: "strategy game style {prompt} . overhead view, detailed map, units, reminiscent of real-time strategy video games",
    negativePrompt: "first-person view, modern, photorealistic",
  },
  {
    id: "game-streetfighter",
    name: "街霸格斗",
    category: "游戏",
    prompt: "Street Fighter style {prompt} . vibrant, dynamic, arcade, 2D fighting game, highly detailed, reminiscent of Street Fighter series",
    negativePrompt: "3D, realistic, modern, photorealistic, turn-based strategy",
  },
  {
    id: "game-zelda",
    name: "塞尔达风",
    category: "游戏",
    prompt: "Legend of Zelda style {prompt} . vibrant, fantasy, detailed, epic, heroic, reminiscent of The Legend of Zelda series",
    negativePrompt: "sci-fi, modern, realistic, horror",
  },
  {
    id: "misc-architectural",
    name: "建筑设计",
    category: "主题",
    prompt: "architectural style {prompt} . clean lines, geometric shapes, minimalist, modern, architectural drawing, highly detailed",
    negativePrompt: "curved lines, ornate, baroque, abstract, grunge",
  },
  {
    id: "misc-disco",
    name: "迪斯科",
    category: "主题",
    prompt: "disco-themed {prompt} . vibrant, groovy, retro 70s style, shiny disco balls, neon lights, dance floor, highly detailed",
    negativePrompt: "minimalist, rustic, monochrome, contemporary, simplistic",
  },
  {
    id: "misc-dreamscape",
    name: "梦境",
    category: "主题",
    prompt: "dreamscape {prompt} . surreal, ethereal, dreamy, mysterious, fantasy, highly detailed",
    negativePrompt: "realistic, concrete, ordinary, mundane",
  },
  {
    id: "misc-dystopian",
    name: "反乌托邦",
    category: "主题",
    prompt: "dystopian style {prompt} . bleak, post-apocalyptic, somber, dramatic, highly detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, cheerful, optimistic, vibrant, colorful",
  },
  {
    id: "misc-fairy tale",
    name: "童话绘本",
    category: "主题",
    prompt: "fairy tale {prompt} . magical, fantastical, enchanting, storybook style, highly detailed",
    negativePrompt: "realistic, modern, ordinary, mundane",
  },
  {
    id: "misc-gothic",
    name: "哥特风",
    category: "主题",
    prompt: "gothic style {prompt} . dark, mysterious, haunting, dramatic, ornate, detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, cheerful, optimistic",
  },
  {
    id: "misc-grunge",
    name: "颓废做旧",
    category: "主题",
    prompt: "grunge style {prompt} . textured, distressed, vintage, edgy, punk rock vibe, dirty, noisy",
    negativePrompt: "smooth, clean, minimalist, sleek, modern, photorealistic",
  },
  {
    id: "misc-horror",
    name: "恐怖惊悚",
    category: "主题",
    prompt: "horror-themed {prompt} . eerie, unsettling, dark, spooky, suspenseful, grim, highly detailed",
    negativePrompt: "cheerful, bright, vibrant, light-hearted, cute",
  },
  {
    id: "misc-kawaii",
    name: "可爱风",
    category: "主题",
    prompt: "kawaii style {prompt} . cute, adorable, brightly colored, cheerful, anime influence, highly detailed",
    negativePrompt: "dark, scary, realistic, monochrome, abstract",
  },
  {
    id: "misc-lovecraftian",
    name: "克苏鲁",
    category: "主题",
    prompt: "lovecraftian horror {prompt} . eldritch, cosmic horror, unknown, mysterious, surreal, highly detailed",
    negativePrompt: "light-hearted, mundane, familiar, simplistic, realistic",
  },
  {
    id: "misc-macabre",
    name: "阴森诡异",
    category: "主题",
    prompt: "macabre style {prompt} . dark, gothic, grim, haunting, highly detailed",
    negativePrompt: "bright, cheerful, light-hearted, cartoonish, cute",
  },
  {
    id: "misc-manga",
    name: "日式漫画",
    category: "主题",
    prompt: "manga style {prompt} . vibrant, high-energy, detailed, iconic, Japanese comic style",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic, Western comic style",
  },
  {
    id: "misc-metropolis",
    name: "大都会",
    category: "主题",
    prompt: "metropolis-themed {prompt} . urban, cityscape, skyscrapers, modern, futuristic, highly detailed",
    negativePrompt: "rural, natural, rustic, historical, simple",
  },
  {
    id: "misc-minimalist",
    name: "极简主义",
    category: "主题",
    prompt: "minimalist style {prompt} . simple, clean, uncluttered, modern, elegant",
    negativePrompt: "ornate, complicated, highly detailed, cluttered, disordered, messy, noisy",
  },
  {
    id: "misc-monochrome",
    name: "黑白单色",
    category: "主题",
    prompt: "monochrome {prompt} . black and white, contrast, tone, texture, detailed",
    negativePrompt: "colorful, vibrant, noisy, blurry, deformed",
  },
  {
    id: "misc-nautical",
    name: "航海风",
    category: "主题",
    prompt: "nautical-themed {prompt} . sea, ocean, ships, maritime, beach, marine life, highly detailed",
    negativePrompt: "landlocked, desert, mountains, urban, rustic",
  },
  {
    id: "misc-space",
    name: "宇宙星空",
    category: "主题",
    prompt: "space-themed {prompt} . cosmic, celestial, stars, galaxies, nebulas, planets, science fiction, highly detailed",
    negativePrompt: "earthly, mundane, ground-based, realism",
  },
  {
    id: "misc-stained glass",
    name: "彩绘玻璃",
    category: "主题",
    prompt: "stained glass style {prompt} . vibrant, beautiful, translucent, intricate, detailed",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic",
  },
  {
    id: "misc-techwear fashion",
    name: "机能风",
    category: "主题",
    prompt: "techwear fashion {prompt} . futuristic, cyberpunk, urban, tactical, sleek, dark, highly detailed",
    negativePrompt: "vintage, rural, colorful, low contrast, realism, sketch, watercolor",
  },
  {
    id: "misc-tribal",
    name: "部落图腾",
    category: "主题",
    prompt: "tribal style {prompt} . indigenous, ethnic, traditional patterns, bold, natural colors, highly detailed",
    negativePrompt: "modern, futuristic, minimalist, pastel",
  },
  {
    id: "misc-zentangle",
    name: "禅绕画",
    category: "主题",
    prompt: "zentangle {prompt} . intricate, abstract, monochrome, patterns, meditative, highly detailed",
    negativePrompt: "colorful, representative, simplistic, large fields of color",
  },
  {
    id: "papercraft-collage",
    name: "拼贴画",
    category: "纸艺",
    prompt: "collage style {prompt} . mixed media, layered, textural, detailed, artistic",
    negativePrompt: "ugly, deformed, noisy, blurry, low contrast, realism, photorealistic",
  },
  {
    id: "papercraft-flat papercut",
    name: "扁平剪纸",
    category: "纸艺",
    prompt: "flat papercut style {prompt} . silhouette, clean cuts, paper, sharp edges, minimalist, color block",
    negativePrompt: "3D, high detail, noise, grainy, blurry, painting, drawing, photo, disfigured",
  },
  {
    id: "papercraft-kirigami",
    name: "立体剪纸",
    category: "纸艺",
    prompt: "kirigami representation of {prompt} . 3D, paper folding, paper cutting, Japanese, intricate, symmetrical, precision, clean lines",
    negativePrompt: "painting, drawing, 2D, noisy, blurry, deformed",
  },
  {
    id: "papercraft-paper mache",
    name: "纸浆工艺",
    category: "纸艺",
    prompt: "paper mache representation of {prompt} . 3D, sculptural, textured, handmade, vibrant, fun",
    negativePrompt: "2D, flat, photo, sketch, digital art, deformed, noisy, blurry",
  },
  {
    id: "papercraft-paper quilling",
    name: "衍纸艺术",
    category: "纸艺",
    prompt: "paper quilling art of {prompt} . intricate, delicate, curling, rolling, shaping, coiling, loops, 3D, dimensional, ornamental",
    negativePrompt: "photo, painting, drawing, 2D, flat, deformed, noisy, blurry",
  },
  {
    id: "papercraft-papercut collage",
    name: "剪纸拼贴",
    category: "纸艺",
    prompt: "papercut collage of {prompt} . mixed media, textured paper, overlapping, asymmetrical, abstract, vibrant",
    negativePrompt: "photo, 3D, realistic, drawing, painting, high detail, disfigured",
  },
  {
    id: "papercraft-papercut shadow box",
    name: "光影纸雕",
    category: "纸艺",
    prompt: "3D papercut shadow box of {prompt} . layered, dimensional, depth, silhouette, shadow, papercut, handmade, high contrast",
    negativePrompt: "painting, drawing, photo, 2D, flat, high detail, blurry, noisy, disfigured",
  },
  {
    id: "papercraft-stacked papercut",
    name: "叠层剪纸",
    category: "纸艺",
    prompt: "stacked papercut art of {prompt} . 3D, layered, dimensional, depth, precision cut, stacked layers, papercut, high contrast",
    negativePrompt: "2D, flat, noisy, blurry, painting, drawing, photo, deformed",
  },
  {
    id: "papercraft-thick layered papercut",
    name: "厚层纸雕",
    category: "纸艺",
    prompt: "thick layered papercut art of {prompt} . deep 3D, volumetric, dimensional, depth, thick paper, high stack, heavy texture, tangible layers",
    negativePrompt: "2D, flat, thin paper, low stack, smooth texture, painting, drawing, photo, deformed",
  },
];

export function getStyleById(id: string | null | undefined): StyleTemplate | undefined {
  if (!id) return undefined;
  return STYLE_LIBRARY.find((style) => style.id === id);
}

export function applyStyleToPrompt(style: StyleTemplate | undefined, userPrompt: string): string {
  if (!style || userPrompt.trim() === "") {
    return userPrompt;
  }
  return style.prompt.split("{prompt}").join(userPrompt);
}

export function mergeStyleNegative(style: StyleTemplate | undefined, userNegative: string): string {
  const styleNegative = style ? style.negativePrompt.trim() : "";
  const user = userNegative.trim();
  if (styleNegative === "") return user;
  if (user === "") return styleNegative;
  // 任一方已完整包含另一方时直接返回，避免重复堆叠
  if (styleNegative.includes(user)) return styleNegative;
  if (user.includes(styleNegative)) return user;
  return styleNegative + "\n" + user;
}
